apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-env
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  DIGDIRATOR_CLUSTER_NAME: "{{ .Values.clusterName | required ".Values.cluster is required." }}"
  DIGDIRATOR_DIGDIR_ADMIN_BASE_URL: "{{ include "adminApiUrl" . }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_CERT_CHAIN: "{{ .Values.idporten.gcpCertChainPath | required ".Values.idporten.gcpCertChainPath is required." }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_CLIENT_ID: "{{ .Values.idporten.gcpClientIdPath | required ".Values.idporten.gcpClientIdPath is required." }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_KMS_KEY_PATH: "{{ .Values.idporten.gcpKmsKeyPath | required ".Values.idporten.gcpKmsKeyPath is required." }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_SCOPES: "{{ .Values.idporten.scopes | required ".Values.idporten.scopes is required." }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_WELL_KNOWN_URL: "{{ .Values.idporten.wellKnownUrl | required ".Values.idporten.wellKnownUrl is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_CERT_CHAIN: "{{ .Values.maskinporten.gcpCertChainPath | required ".Values.maskinporten.gcpCertChainPath is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_CLIENT_ID: "{{ .Values.maskinporten.gcpClientIdPath | required ".Values.maskinporten.gcpClientIdPath is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_KMS_KEY_PATH: "{{ .Values.maskinporten.gcpKmsKeyPath | required ".Values.maskinporten.gcpKmsKeyPath is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_SCOPES: "{{ .Values.maskinporten.scopes | required ".Values.maskinporten.scopes is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_WELL_KNOWN_URL: "{{ .Values.maskinporten.wellKnownUrl | required ".Values.maskinporten.wellKnownUrl is required." }}"
  DIGDIRATOR_FEATURES_MASKINPORTEN: "true"

{{- if .Values.onprem.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-google-service-account
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  sa.json: |
    {{ .Values.onprem.gcpSaCredentials | required ".Values.onprem.gcpSaCredentials is required." }}
{{ end }}
