apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-env
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  DIGDIRATOR_CLUSTER_NAME: "{{ .Values.clusterName | required ".Values.clusterName is required." }}"
  DIGDIRATOR_DIGDIR_ADMIN_BASE_URL: "{{ include "adminApiUrl" . }}"
  DIGDIRATOR_DIGDIR_ADMIN_CLIENT_ID: "{{ .Values.admin.clientID | required ".Values.admin.clientID is required." }}"
  DIGDIRATOR_DIGDIR_ADMIN_CERT_CHAIN: |-
    {{- .Values.admin.certChain | required ".Values.admin.certChain is required." | b64dec | nindent 4 }}
  DIGDIRATOR_DIGDIR_ADMIN_KMS_KEY_PATH: "{{ .Values.admin.gcpKmsKeyPath | required ".Values.admin.gcpKmsKeyPath is required." }}"
  DIGDIRATOR_DIGDIR_ADMIN_SCOPES: "{{ .Values.admin.scopes | required ".Values.admin.scopes is required." }}"
  DIGDIRATOR_DIGDIR_IDPORTEN_WELL_KNOWN_URL: "{{ .Values.idporten.wellKnownUrl | required ".Values.idporten.wellKnownUrl is required." }}"
  DIGDIRATOR_DIGDIR_MASKINPORTEN_WELL_KNOWN_URL: "{{ .Values.maskinporten.wellKnownUrl | required ".Values.maskinporten.wellKnownUrl is required." }}"
  DIGDIRATOR_FEATURES_MASKINPORTEN: "true"

{{- if .Values.onprem.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-google-service-account
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  sa.json: |
    {{ .Values.onprem.gcpSaCredentials | required ".Values.onprem.gcpSaCredentials is required." }}
{{ end }}
