apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-env
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  {{- range $key, $value := .Values.digdirator.secrets.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

{{- if .Values.digdirator.onprem.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: digdirator-google-service-account
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  sa.json: |
    {{- .Values.digdirator.secrets.google.sa.credentials | default "" | nindent 4 }}
{{ end }}