{{ if not .Values.digdirator.onprem.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "digdirator.serviceAccountName" . }}
  labels:
    {{- include "digdirator.labels" . | nindent 4 }}
{{ end }}