dependencies:
  - allOf:
      - naiserator
      - nais-crds
      - replicator
environmentKinds:
  - tenant
  - onprem
  - legacy
values:
  adminApiHost:
    description: Host for DigDir Admin API. See https://docs.digdir.no/docs/idporten/oidc/oidc_api_admin#endepunkter
    required: true
    config:
      type: string
  apiserverIP:
    computed:
      template: '"{{ .Env.apiserver_endpoint }}"'
  clusterName:
    description: Cluster name override for equivalent mapping value.
    computed:
      template: '"{{ .Env.name }}"'
    config:
      type: string
  idporten.gcpCertChainPath:
    description: Path to Secret Manager secret containing cert chain for ID-porten admin client
    required: true
    config:
      type: string
  idporten.gcpClientIdPath:
    description: Path to Secret Manager secret containing client ID for ID-porten admin client
    required: true
    config:
      type: string
  idporten.gcpKmsKeyPath:
    description: Path to Cloud KMS key for ID-porten admin client
    required: true
    config:
      type: string
  idporten.hosts:
    description: Hosts for ID-porten, used for egress network policies for pods with label idporten=enabled
    required: true
    config:
      type: string_array
    ignoreKind:
      - onprem
  idporten.wellKnownUrl:
    description: ID-porten well-known URL. See https://docs.digdir.no/docs/idporten/oidc/oidc_func_wellknown.html
    required: true
    config:
      type: string
  image.tag:
    description: Image tag for digdirator
    config:
      type: string
  maskinporten.gcpCertChainPath:
    description: Path to Secret Manager secret containing cert chain for Maskinporten admin client
    required: true
    config:
      type: string
  maskinporten.gcpClientIdPath:
    description: Path to Secret Manager secret containing client ID for Maskinporten admin client
    required: true
    config:
      type: string
  maskinporten.gcpKmsKeyPath:
    description: Path to Cloud KMS key for Maskinporten admin client
    required: true
    config:
      type: string
  maskinporten.hosts:
    description: Hosts for Maskinporten, used for egress network policies for pods with label maskinporten=enabled
    required: true
    config:
      type: string_array
    ignoreKind:
      - onprem
  maskinporten.wellKnownUrl:
    description: Maskinporten well-known URL. See https://docs.digdir.no/docs/Maskinporten/maskinporten_func_wellknown
    required: true
    config:
      type: string
  onprem.enabled:
    description: Enable resources for onprem
    computed:
      template: '{{ eq .Kind "onprem" }}'
    ignoreKind:
      - tenant
      - legacy
  onprem.gcpSaCredentials:
    description: SA Credentials for accessing Cloud KMS from onprem. Required if onprem is enabled
    config:
      type: string
      secret: true
    ignoreKind:
      - tenant
      - legacy
