dependencies:
  - allOf:
      - naiserator
      - nais-crds
      - replicator
environmentKinds:
  - tenant
  - onprem
  - legacy
values:
  admin.apiHost:
    description: Host for DigDir Admin API. See https://docs.digdir.no/docs/idporten/oidc/oidc_api_admin#endepunkter
    required: true
    config:
      type: string
  admin.clientID:
    description: Client ID / issuer for JWT assertion when authenticating with DigDir self service API
    required: true
    config:
      type: string
  admin.certChain:
    description: Base64 encoded string of full certificate chain in PEM format for business certificate used to sign JWT assertion
    required: true
    config:
      type: string
      secret: true
  admin.gcpKmsKeyPath:
    description: Resource path to Google KMS crypto key version used to sign JWT assertion
    required: true
    config:
      type: string
  admin.scopes:
    description: List of space-separated scopes for JWT assertion when authenticating with DigDir self service API
    config:
      type: string
  apiserverIP:
    computed:
      template: '"{{ .Env.apiserver_endpoint }}"'
  clusterName:
    description: Cluster name override for equivalent mapping value.
    computed:
      template: '"{{ .Env.name }}"'
    config:
      type: string
  idporten.wellKnownUrl:
    description: ID-porten well-known URL. See https://docs.digdir.no/docs/idporten/oidc/oidc_func_wellknown.html
    required: true
    config:
      type: string
  image.tag:
    description: Image tag for digdirator
    config:
      type: string
  maskinporten.wellKnownUrl:
    description: Maskinporten well-known URL. See https://docs.digdir.no/docs/Maskinporten/maskinporten_func_wellknown
    required: true
    config:
      type: string
  onprem.enabled:
    description: Enable resources for onprem
    computed:
      template: '{{ eq .Kind "onprem" }}'
    ignoreKind:
      - tenant
      - legacy
  onprem.gcpSaCredentials:
    description: SA Credentials for accessing Cloud KMS from onprem. Required if onprem is enabled
    config:
      type: string
      secret: true
    ignoreKind:
      - tenant
      - legacy
