---
apiVersion: nais.io/v1
kind: IDPortenClient
metadata:
  name: my-app
spec:
  clientName: "my app test 2"
  clientURI: "https://min-app.nav.no"
  redirectURI: https://min-app.nav.no/oauth2/callback
  secretName: my-secret
  frontchannelLogoutURI: "https://min-app.nav.no/oauth2/logout"
  postLogoutRedirectURIs:
    - "https://nav.no"
  refreshTokenLifetime: 3601
