---
apiVersion: nais.io/v1
kind: IDPortenClient
metadata:
  name: my-app
  namespace: myteam
spec:
  applicationType: "web"
  clientURI: "https://min-app.nav.no"
  redirectURIs:
    - https://min-app.nav.no/oauth2/callback
  secretName: my-secret
  frontchannelLogoutURI: "https://min-app.nav.no/oauth2/logout"
  postLogoutRedirectURIs:
    - "https://nav.no"
  accessTokenLifetime: 3600
  sessionLifetime: 28800
  ssoDisabled: false
