@startuml component
title Digdirator Sequence Flow
skinparam maxMessageSize 300
autonumber

actor developer as "Developer"
control digdirator as "Digdirator"

box "Cluster resources"
participant IDPortenClient
participant Secret
participant Application
end box

participant digdir as "DigDir"
actor enduser as "End User"

==On create / update==
developer -> IDPortenClient: Apply config

loop forever
	digdirator -> IDPortenClient: watch for updates
end

digdirator -> digdir: check if client exists
digdirator -> digdir: register / update client
digdirator -> digdirator: generate new set of JWK
digdirator -> digdir: register new JWKS

group client already exists in ID-Porten
    digdirator -> Secret: fetch existing JWK
    digdirator -> digdir: register JWKS, with new and existing JWK
end

digdirator -> IDPortenClient: update status subresource
digdirator -> Secret: inject JWK and metadata

== Usage ==

Secret -> Application: mount
enduser -> Application: log in
Application -> digdir: start OIDC auth code flow
Application -> enduser: redirect to DigDir
enduser -> digdir: authenticates
digdir -> Application: auth code
Application -> digdir: signed JWT, auth code, state
digdir -> Application: id_token, access_token, (refresh_token)
Application -> enduser: signed in

==On deletion==
    developer -> IDPortenClient: delete
    digdirator -> Secret: delete
    digdirator -> digdir: delete

@enduml
